export enum VERIFIED_PRESENTATIONS_ACTION_TYPES {
  REQUEST_VERIFIED_PRESENTATIONS = 'REQUEST_VERIFIED_PRESENTATIONS',
  RECEIVE_VERIFIED_PRESENTATIONS = 'RECEIVE_VERIFIED_PRESENTATIONS',
  RECEIVE_EMPTY_VERIFIED_PRESENTATIONS = 'RECEIVE_EMPTY_VERIFIED_PRESENTATIONS',
}

export const requestVerifiedPresentations = () => ({
  type: VERIFIED_PRESENTATIONS_ACTION_TYPES.REQUEST_VERIFIED_PRESENTATIONS,
});

export const receiveVerifiedPresentations = (presentations: string) => ({
  type: VERIFIED_PRESENTATIONS_ACTION_TYPES.RECEIVE_VERIFIED_PRESENTATIONS,
  presentations,
});

export const receiveEmptyVerifiedPresentations = () => ({
  type: VERIFIED_PRESENTATIONS_ACTION_TYPES.REQUEST_VERIFIED_PRESENTATIONS,
})