export enum SCANNED_PRESENTATIONS_ACTION_TYPES {
  REQUEST_SCANNED_PRESENTATIONS = 'REQUEST_SCANNED_PRESENTATIONS',
  RECEIVE_SCANNED_PRESENTATIONS = 'RECEIVE_SCANNED_PRESENTATIONS',
  RECEIVE_EMPTY_SCANNED_PRESENTATIONS = 'RECEIVE_EMPTY_SCANNED_PRESENTATIONS',
}

export const requestScannedPresentations = () => ({
  type: SCANNED_PRESENTATIONS_ACTION_TYPES.REQUEST_SCANNED_PRESENTATIONS,
});

export const receiveScannedPresentations = (presentations: string) => ({
  type: SCANNED_PRESENTATIONS_ACTION_TYPES.RECEIVE_SCANNED_PRESENTATIONS,
  presentations,
});

export const receiveEmptyScannedPresentations = () => ({
  type: SCANNED_PRESENTATIONS_ACTION_TYPES.REQUEST_SCANNED_PRESENTATIONS,
})